// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run the FlutterFire CLI again to fix this.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07SVsu0lF_v6NDc-9qt9Kaa2J4N9TlZY',
    appId: '1:97099869283:web:5a24d6689c05c427b55c56',
    messagingSenderId: '97099869283',
    projectId: 'fixit-app-17f73',
    authDomain: 'fixit-app-17f73.firebaseapp.com',
    storageBucket: 'fixit-app-17f73.appspot.com', // ✅ FIXED
    measurementId: 'G-KC5X15WBH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTLMzZiNpQkbhq5Au2r5Rk--aw8LfVG0',
    appId: '1:97099869283:android:2d7d616829345dcab55c56',
    messagingSenderId: '97099869283',
    projectId: 'fixit-app-17f73',
    storageBucket: 'fixit-app-17f73.appspot.com', // ✅ FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDinl7SGaAm90DPmvqWc8vHmbQ_NfdDw',
    appId: '1:97099869283:ios:c04ab025966392e9b55c56',
    messagingSenderId: '97099869283',
    projectId: 'fixit-app-17f73',
    storageBucket: 'fixit-app-17f73.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxDinl7SGaAm90DPmvqWc8vHmbQ_NfdDw',
    appId: '1:97099869283:ios:c04ab025966392e9b55c56',
    messagingSenderId: '97099869283',
    projectId: 'fixit-app-17f73',
    storageBucket: 'fixit-app-17f73.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.fixitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD07SVsu0lF_v6NDc-9qt9Kaa2J4N9TlZY',
    appId: '1:97099869283:web:824d2f2aa0d4a960b55c56',
    messagingSenderId: '97099869283',
    projectId: 'fixit-app-17f73',
    authDomain: 'fixit-app-17f73.firebaseapp.com',
    storageBucket: 'fixit-app-17f73.appspot.com', // ✅ FIXED
    measurementId: 'G-E938MVNR0M',
  );
}
